from datetime import datetime
from typing import Protocol

from app.domain.models import Analysis, ResumeFields, ResumeRecord, Session


class ResumeRepository(Protocol):
    def create(self, session: Session, filename: str, fields: ResumeFields) -> ResumeRecord: ...
    def get(self, owner: str, resume_id: str) -> ResumeRecord: ...
    def list(self, owner: str) -> list[ResumeRecord]: ...
    def save(
        self, owner: str, resume_id: str, revision: int, fields: ResumeFields
    ) -> ResumeRecord: ...
    def review(
        self, owner: str, resume_id: str, revision: int, analysis: Analysis, jd_text: str
    ) -> ResumeRecord: ...
    def delete(self, owner: str, resume_id: str) -> None: ...
    def delete_owner(self, owner: str) -> None: ...
    def purge_expired(self, now: datetime) -> int: ...
    def health(self) -> None: ...


class SessionStore(Protocol):
    def create(self, client_id: str, owner: str | None = None) -> str: ...
    def resolve(self, token: str | None) -> Session: ...
    def delete(self, token: str) -> None: ...
    def consume_analysis(self, session: Session) -> None: ...
    def consume_auth(self, client_id: str) -> None: ...
    def health(self) -> None: ...


class ResumeReviewer(Protocol):
    def analyze(self, fields: ResumeFields, jd_text: str) -> Analysis: ...


class DocumentProcessor(Protocol):
    def extract(self, filename: str, data: bytes) -> ResumeFields: ...
    def pdf(self, fields: ResumeFields, template: str = "modern") -> bytes: ...
