"""Career aggregate contracts: no framework or persistence dependencies."""

from dataclasses import dataclass
from typing import Any, Protocol

from app.domain.models import Session


@dataclass
class CareerRecord:
    id: str
    revision: int
    data: dict[str, Any]
    created_at: str


class CareerRepository(Protocol):
    def create(
        self, kind: str, session: Session, data: dict, record_id: str | None = None
    ) -> CareerRecord: ...
    def get(self, kind: str, owner: str, record_id: str) -> CareerRecord: ...
    def list(self, kind: str, owner: str) -> list[CareerRecord]: ...
    def update(
        self, kind: str, owner: str, record_id: str, revision: int, data: dict
    ) -> CareerRecord: ...
    def delete(self, kind: str, owner: str, record_id: str) -> None: ...
    def clear(self, owner: str) -> None: ...
    def register(self, email: str, password_hash: str, owner: str) -> None: ...
    def account(self, email: str) -> dict: ...
    def promote(self, owner: str) -> None: ...


class CareerCoach(Protocol):
    def improvements(self, fields: dict, profile: dict, job: str) -> dict: ...
    def questions(self, context: dict) -> dict: ...
    def evaluate(self, context: dict, question: dict, answer: str) -> dict: ...
    def plan(self, profile: dict, goal: str, gaps: list[str]) -> dict: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, encoded: str) -> bool: ...
